// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: dota_gcmessages_client_bingo.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMsgClientToGCBingoGetUserDataResponse_EResponse int32

const (
	CMsgClientToGCBingoGetUserDataResponse_k_eInternalError CMsgClientToGCBingoGetUserDataResponse_EResponse = 0
	CMsgClientToGCBingoGetUserDataResponse_k_eSuccess       CMsgClientToGCBingoGetUserDataResponse_EResponse = 1
	CMsgClientToGCBingoGetUserDataResponse_k_eTooBusy       CMsgClientToGCBingoGetUserDataResponse_EResponse = 2
	CMsgClientToGCBingoGetUserDataResponse_k_eDisabled      CMsgClientToGCBingoGetUserDataResponse_EResponse = 3
	CMsgClientToGCBingoGetUserDataResponse_k_eTimeout       CMsgClientToGCBingoGetUserDataResponse_EResponse = 4
)

// Enum value maps for CMsgClientToGCBingoGetUserDataResponse_EResponse.
var (
	CMsgClientToGCBingoGetUserDataResponse_EResponse_name = map[int32]string{
		0: "k_eInternalError",
		1: "k_eSuccess",
		2: "k_eTooBusy",
		3: "k_eDisabled",
		4: "k_eTimeout",
	}
	CMsgClientToGCBingoGetUserDataResponse_EResponse_value = map[string]int32{
		"k_eInternalError": 0,
		"k_eSuccess":       1,
		"k_eTooBusy":       2,
		"k_eDisabled":      3,
		"k_eTimeout":       4,
	}
)

func (x CMsgClientToGCBingoGetUserDataResponse_EResponse) Enum() *CMsgClientToGCBingoGetUserDataResponse_EResponse {
	p := new(CMsgClientToGCBingoGetUserDataResponse_EResponse)
	*p = x
	return p
}

func (x CMsgClientToGCBingoGetUserDataResponse_EResponse) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CMsgClientToGCBingoGetUserDataResponse_EResponse) Descriptor() protoreflect.EnumDescriptor {
	return file_dota_gcmessages_client_bingo_proto_enumTypes[0].Descriptor()
}

func (CMsgClientToGCBingoGetUserDataResponse_EResponse) Type() protoreflect.EnumType {
	return &file_dota_gcmessages_client_bingo_proto_enumTypes[0]
}

func (x CMsgClientToGCBingoGetUserDataResponse_EResponse) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CMsgClientToGCBingoGetUserDataResponse_EResponse) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CMsgClientToGCBingoGetUserDataResponse_EResponse(num)
	return nil
}

// Deprecated: Use CMsgClientToGCBingoGetUserDataResponse_EResponse.Descriptor instead.
func (CMsgClientToGCBingoGetUserDataResponse_EResponse) EnumDescriptor() ([]byte, []int) {
	return file_dota_gcmessages_client_bingo_proto_rawDescGZIP(), []int{3, 0}
}

type CMsgClientToGCBingoGetStatsDataResponse_EResponse int32

const (
	CMsgClientToGCBingoGetStatsDataResponse_k_eInternalError CMsgClientToGCBingoGetStatsDataResponse_EResponse = 0
	CMsgClientToGCBingoGetStatsDataResponse_k_eSuccess       CMsgClientToGCBingoGetStatsDataResponse_EResponse = 1
	CMsgClientToGCBingoGetStatsDataResponse_k_eTooBusy       CMsgClientToGCBingoGetStatsDataResponse_EResponse = 2
	CMsgClientToGCBingoGetStatsDataResponse_k_eDisabled      CMsgClientToGCBingoGetStatsDataResponse_EResponse = 3
	CMsgClientToGCBingoGetStatsDataResponse_k_eTimeout       CMsgClientToGCBingoGetStatsDataResponse_EResponse = 4
)

// Enum value maps for CMsgClientToGCBingoGetStatsDataResponse_EResponse.
var (
	CMsgClientToGCBingoGetStatsDataResponse_EResponse_name = map[int32]string{
		0: "k_eInternalError",
		1: "k_eSuccess",
		2: "k_eTooBusy",
		3: "k_eDisabled",
		4: "k_eTimeout",
	}
	CMsgClientToGCBingoGetStatsDataResponse_EResponse_value = map[string]int32{
		"k_eInternalError": 0,
		"k_eSuccess":       1,
		"k_eTooBusy":       2,
		"k_eDisabled":      3,
		"k_eTimeout":       4,
	}
)

func (x CMsgClientToGCBingoGetStatsDataResponse_EResponse) Enum() *CMsgClientToGCBingoGetStatsDataResponse_EResponse {
	p := new(CMsgClientToGCBingoGetStatsDataResponse_EResponse)
	*p = x
	return p
}

func (x CMsgClientToGCBingoGetStatsDataResponse_EResponse) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CMsgClientToGCBingoGetStatsDataResponse_EResponse) Descriptor() protoreflect.EnumDescriptor {
	return file_dota_gcmessages_client_bingo_proto_enumTypes[1].Descriptor()
}

func (CMsgClientToGCBingoGetStatsDataResponse_EResponse) Type() protoreflect.EnumType {
	return &file_dota_gcmessages_client_bingo_proto_enumTypes[1]
}

func (x CMsgClientToGCBingoGetStatsDataResponse_EResponse) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CMsgClientToGCBingoGetStatsDataResponse_EResponse) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CMsgClientToGCBingoGetStatsDataResponse_EResponse(num)
	return nil
}

// Deprecated: Use CMsgClientToGCBingoGetStatsDataResponse_EResponse.Descriptor instead.
func (CMsgClientToGCBingoGetStatsDataResponse_EResponse) EnumDescriptor() ([]byte, []int) {
	return file_dota_gcmessages_client_bingo_proto_rawDescGZIP(), []int{7, 0}
}

type CMsgClientToGCBingoClaimRowResponse_EResponse int32

const (
	CMsgClientToGCBingoClaimRowResponse_k_eInternalError CMsgClientToGCBingoClaimRowResponse_EResponse = 0
	CMsgClientToGCBingoClaimRowResponse_k_eSuccess       CMsgClientToGCBingoClaimRowResponse_EResponse = 1
	CMsgClientToGCBingoClaimRowResponse_k_eTooBusy       CMsgClientToGCBingoClaimRowResponse_EResponse = 2
	CMsgClientToGCBingoClaimRowResponse_k_eDisabled      CMsgClientToGCBingoClaimRowResponse_EResponse = 3
	CMsgClientToGCBingoClaimRowResponse_k_eTimeout       CMsgClientToGCBingoClaimRowResponse_EResponse = 4
	CMsgClientToGCBingoClaimRowResponse_k_eInvalidRow    CMsgClientToGCBingoClaimRowResponse_EResponse = 5
	CMsgClientToGCBingoClaimRowResponse_k_eExpiredCard   CMsgClientToGCBingoClaimRowResponse_EResponse = 6
)

// Enum value maps for CMsgClientToGCBingoClaimRowResponse_EResponse.
var (
	CMsgClientToGCBingoClaimRowResponse_EResponse_name = map[int32]string{
		0: "k_eInternalError",
		1: "k_eSuccess",
		2: "k_eTooBusy",
		3: "k_eDisabled",
		4: "k_eTimeout",
		5: "k_eInvalidRow",
		6: "k_eExpiredCard",
	}
	CMsgClientToGCBingoClaimRowResponse_EResponse_value = map[string]int32{
		"k_eInternalError": 0,
		"k_eSuccess":       1,
		"k_eTooBusy":       2,
		"k_eDisabled":      3,
		"k_eTimeout":       4,
		"k_eInvalidRow":    5,
		"k_eExpiredCard":   6,
	}
)

func (x CMsgClientToGCBingoClaimRowResponse_EResponse) Enum() *CMsgClientToGCBingoClaimRowResponse_EResponse {
	p := new(CMsgClientToGCBingoClaimRowResponse_EResponse)
	*p = x
	return p
}

func (x CMsgClientToGCBingoClaimRowResponse_EResponse) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CMsgClientToGCBingoClaimRowResponse_EResponse) Descriptor() protoreflect.EnumDescriptor {
	return file_dota_gcmessages_client_bingo_proto_enumTypes[2].Descriptor()
}

func (CMsgClientToGCBingoClaimRowResponse_EResponse) Type() protoreflect.EnumType {
	return &file_dota_gcmessages_client_bingo_proto_enumTypes[2]
}

func (x CMsgClientToGCBingoClaimRowResponse_EResponse) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CMsgClientToGCBingoClaimRowResponse_EResponse) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CMsgClientToGCBingoClaimRowResponse_EResponse(num)
	return nil
}

// Deprecated: Use CMsgClientToGCBingoClaimRowResponse_EResponse.Descriptor instead.
func (CMsgClientToGCBingoClaimRowResponse_EResponse) EnumDescriptor() ([]byte, []int) {
	return file_dota_gcmessages_client_bingo_proto_rawDescGZIP(), []int{10, 0}
}

type CMsgClientToGCBingoDevRerollCardResponse_EResponse int32

const (
	CMsgClientToGCBingoDevRerollCardResponse_k_eInternalError CMsgClientToGCBingoDevRerollCardResponse_EResponse = 0
	CMsgClientToGCBingoDevRerollCardResponse_k_eSuccess       CMsgClientToGCBingoDevRerollCardResponse_EResponse = 1
	CMsgClientToGCBingoDevRerollCardResponse_k_eTooBusy       CMsgClientToGCBingoDevRerollCardResponse_EResponse = 2
	CMsgClientToGCBingoDevRerollCardResponse_k_eDisabled      CMsgClientToGCBingoDevRerollCardResponse_EResponse = 3
	CMsgClientToGCBingoDevRerollCardResponse_k_eTimeout       CMsgClientToGCBingoDevRerollCardResponse_EResponse = 4
	CMsgClientToGCBingoDevRerollCardResponse_k_eExpiredCard   CMsgClientToGCBingoDevRerollCardResponse_EResponse = 6
	CMsgClientToGCBingoDevRerollCardResponse_k_eNotAllowed    CMsgClientToGCBingoDevRerollCardResponse_EResponse = 7
)

// Enum value maps for CMsgClientToGCBingoDevRerollCardResponse_EResponse.
var (
	CMsgClientToGCBingoDevRerollCardResponse_EResponse_name = map[int32]string{
		0: "k_eInternalError",
		1: "k_eSuccess",
		2: "k_eTooBusy",
		3: "k_eDisabled",
		4: "k_eTimeout",
		6: "k_eExpiredCard",
		7: "k_eNotAllowed",
	}
	CMsgClientToGCBingoDevRerollCardResponse_EResponse_value = map[string]int32{
		"k_eInternalError": 0,
		"k_eSuccess":       1,
		"k_eTooBusy":       2,
		"k_eDisabled":      3,
		"k_eTimeout":       4,
		"k_eExpiredCard":   6,
		"k_eNotAllowed":    7,
	}
)

func (x CMsgClientToGCBingoDevRerollCardResponse_EResponse) Enum() *CMsgClientToGCBingoDevRerollCardResponse_EResponse {
	p := new(CMsgClientToGCBingoDevRerollCardResponse_EResponse)
	*p = x
	return p
}

func (x CMsgClientToGCBingoDevRerollCardResponse_EResponse) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CMsgClientToGCBingoDevRerollCardResponse_EResponse) Descriptor() protoreflect.EnumDescriptor {
	return file_dota_gcmessages_client_bingo_proto_enumTypes[3].Descriptor()
}

func (CMsgClientToGCBingoDevRerollCardResponse_EResponse) Type() protoreflect.EnumType {
	return &file_dota_gcmessages_client_bingo_proto_enumTypes[3]
}

func (x CMsgClientToGCBingoDevRerollCardResponse_EResponse) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CMsgClientToGCBingoDevRerollCardResponse_EResponse) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CMsgClientToGCBingoDevRerollCardResponse_EResponse(num)
	return nil
}

// Deprecated: Use CMsgClientToGCBingoDevRerollCardResponse_EResponse.Descriptor instead.
func (CMsgClientToGCBingoDevRerollCardResponse_EResponse) EnumDescriptor() ([]byte, []int) {
	return file_dota_gcmessages_client_bingo_proto_rawDescGZIP(), []int{12, 0}
}

type CMsgBingoSquare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatId        *uint32                `protobuf:"varint,1,opt,name=stat_id,json=statId" json:"stat_id,omitempty"`
	StatThreshold *int32                 `protobuf:"varint,2,opt,name=stat_threshold,json=statThreshold" json:"stat_threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgBingoSquare) Reset() {
	*x = CMsgBingoSquare{}
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgBingoSquare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgBingoSquare) ProtoMessage() {}

func (x *CMsgBingoSquare) ProtoReflect() protoreflect.Message {
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgBingoSquare.ProtoReflect.Descriptor instead.
func (*CMsgBingoSquare) Descriptor() ([]byte, []int) {
	return file_dota_gcmessages_client_bingo_proto_rawDescGZIP(), []int{0}
}

func (x *CMsgBingoSquare) GetStatId() uint32 {
	if x != nil && x.StatId != nil {
		return *x.StatId
	}
	return 0
}

func (x *CMsgBingoSquare) GetStatThreshold() int32 {
	if x != nil && x.StatThreshold != nil {
		return *x.StatThreshold
	}
	return 0
}

type CMsgBingoUserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Squares       []*CMsgBingoSquare     `protobuf:"bytes,1,rep,name=squares" json:"squares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgBingoUserData) Reset() {
	*x = CMsgBingoUserData{}
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgBingoUserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgBingoUserData) ProtoMessage() {}

func (x *CMsgBingoUserData) ProtoReflect() protoreflect.Message {
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgBingoUserData.ProtoReflect.Descriptor instead.
func (*CMsgBingoUserData) Descriptor() ([]byte, []int) {
	return file_dota_gcmessages_client_bingo_proto_rawDescGZIP(), []int{1}
}

func (x *CMsgBingoUserData) GetSquares() []*CMsgBingoSquare {
	if x != nil {
		return x.Squares
	}
	return nil
}

type CMsgClientToGCBingoGetUserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeagueId      *uint32                `protobuf:"varint,1,opt,name=league_id,json=leagueId" json:"league_id,omitempty"`
	LeaguePhase   *uint32                `protobuf:"varint,2,opt,name=league_phase,json=leaguePhase" json:"league_phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientToGCBingoGetUserData) Reset() {
	*x = CMsgClientToGCBingoGetUserData{}
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientToGCBingoGetUserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientToGCBingoGetUserData) ProtoMessage() {}

func (x *CMsgClientToGCBingoGetUserData) ProtoReflect() protoreflect.Message {
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientToGCBingoGetUserData.ProtoReflect.Descriptor instead.
func (*CMsgClientToGCBingoGetUserData) Descriptor() ([]byte, []int) {
	return file_dota_gcmessages_client_bingo_proto_rawDescGZIP(), []int{2}
}

func (x *CMsgClientToGCBingoGetUserData) GetLeagueId() uint32 {
	if x != nil && x.LeagueId != nil {
		return *x.LeagueId
	}
	return 0
}

func (x *CMsgClientToGCBingoGetUserData) GetLeaguePhase() uint32 {
	if x != nil && x.LeaguePhase != nil {
		return *x.LeaguePhase
	}
	return 0
}

type CMsgClientToGCBingoGetUserDataResponse struct {
	state         protoimpl.MessageState                            `protogen:"open.v1"`
	Response      *CMsgClientToGCBingoGetUserDataResponse_EResponse `protobuf:"varint,1,opt,name=response,enum=protocol.CMsgClientToGCBingoGetUserDataResponse_EResponse,def=0" json:"response,omitempty"`
	UserData      *CMsgBingoUserData                                `protobuf:"bytes,2,opt,name=user_data,json=userData" json:"user_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CMsgClientToGCBingoGetUserDataResponse fields.
const (
	Default_CMsgClientToGCBingoGetUserDataResponse_Response = CMsgClientToGCBingoGetUserDataResponse_k_eInternalError
)

func (x *CMsgClientToGCBingoGetUserDataResponse) Reset() {
	*x = CMsgClientToGCBingoGetUserDataResponse{}
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientToGCBingoGetUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientToGCBingoGetUserDataResponse) ProtoMessage() {}

func (x *CMsgClientToGCBingoGetUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientToGCBingoGetUserDataResponse.ProtoReflect.Descriptor instead.
func (*CMsgClientToGCBingoGetUserDataResponse) Descriptor() ([]byte, []int) {
	return file_dota_gcmessages_client_bingo_proto_rawDescGZIP(), []int{3}
}

func (x *CMsgClientToGCBingoGetUserDataResponse) GetResponse() CMsgClientToGCBingoGetUserDataResponse_EResponse {
	if x != nil && x.Response != nil {
		return *x.Response
	}
	return Default_CMsgClientToGCBingoGetUserDataResponse_Response
}

func (x *CMsgClientToGCBingoGetUserDataResponse) GetUserData() *CMsgBingoUserData {
	if x != nil {
		return x.UserData
	}
	return nil
}

type CMsgBingoIndividualStatData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatId        *uint32                `protobuf:"varint,1,opt,name=stat_id,json=statId" json:"stat_id,omitempty"`
	StatValue     *int32                 `protobuf:"varint,2,opt,name=stat_value,json=statValue" json:"stat_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgBingoIndividualStatData) Reset() {
	*x = CMsgBingoIndividualStatData{}
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgBingoIndividualStatData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgBingoIndividualStatData) ProtoMessage() {}

func (x *CMsgBingoIndividualStatData) ProtoReflect() protoreflect.Message {
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgBingoIndividualStatData.ProtoReflect.Descriptor instead.
func (*CMsgBingoIndividualStatData) Descriptor() ([]byte, []int) {
	return file_dota_gcmessages_client_bingo_proto_rawDescGZIP(), []int{4}
}

func (x *CMsgBingoIndividualStatData) GetStatId() uint32 {
	if x != nil && x.StatId != nil {
		return *x.StatId
	}
	return 0
}

func (x *CMsgBingoIndividualStatData) GetStatValue() int32 {
	if x != nil && x.StatValue != nil {
		return *x.StatValue
	}
	return 0
}

type CMsgBingoStatsData struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	StatsData     []*CMsgBingoIndividualStatData `protobuf:"bytes,1,rep,name=stats_data,json=statsData" json:"stats_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgBingoStatsData) Reset() {
	*x = CMsgBingoStatsData{}
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgBingoStatsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgBingoStatsData) ProtoMessage() {}

func (x *CMsgBingoStatsData) ProtoReflect() protoreflect.Message {
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgBingoStatsData.ProtoReflect.Descriptor instead.
func (*CMsgBingoStatsData) Descriptor() ([]byte, []int) {
	return file_dota_gcmessages_client_bingo_proto_rawDescGZIP(), []int{5}
}

func (x *CMsgBingoStatsData) GetStatsData() []*CMsgBingoIndividualStatData {
	if x != nil {
		return x.StatsData
	}
	return nil
}

type CMsgClientToGCBingoGetStatsData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeagueId      *uint32                `protobuf:"varint,1,opt,name=league_id,json=leagueId" json:"league_id,omitempty"`
	LeaguePhase   *uint32                `protobuf:"varint,2,opt,name=league_phase,json=leaguePhase" json:"league_phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientToGCBingoGetStatsData) Reset() {
	*x = CMsgClientToGCBingoGetStatsData{}
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientToGCBingoGetStatsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientToGCBingoGetStatsData) ProtoMessage() {}

func (x *CMsgClientToGCBingoGetStatsData) ProtoReflect() protoreflect.Message {
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientToGCBingoGetStatsData.ProtoReflect.Descriptor instead.
func (*CMsgClientToGCBingoGetStatsData) Descriptor() ([]byte, []int) {
	return file_dota_gcmessages_client_bingo_proto_rawDescGZIP(), []int{6}
}

func (x *CMsgClientToGCBingoGetStatsData) GetLeagueId() uint32 {
	if x != nil && x.LeagueId != nil {
		return *x.LeagueId
	}
	return 0
}

func (x *CMsgClientToGCBingoGetStatsData) GetLeaguePhase() uint32 {
	if x != nil && x.LeaguePhase != nil {
		return *x.LeaguePhase
	}
	return 0
}

type CMsgClientToGCBingoGetStatsDataResponse struct {
	state         protoimpl.MessageState                             `protogen:"open.v1"`
	Response      *CMsgClientToGCBingoGetStatsDataResponse_EResponse `protobuf:"varint,1,opt,name=response,enum=protocol.CMsgClientToGCBingoGetStatsDataResponse_EResponse,def=0" json:"response,omitempty"`
	StatsData     *CMsgBingoStatsData                                `protobuf:"bytes,2,opt,name=stats_data,json=statsData" json:"stats_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CMsgClientToGCBingoGetStatsDataResponse fields.
const (
	Default_CMsgClientToGCBingoGetStatsDataResponse_Response = CMsgClientToGCBingoGetStatsDataResponse_k_eInternalError
)

func (x *CMsgClientToGCBingoGetStatsDataResponse) Reset() {
	*x = CMsgClientToGCBingoGetStatsDataResponse{}
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientToGCBingoGetStatsDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientToGCBingoGetStatsDataResponse) ProtoMessage() {}

func (x *CMsgClientToGCBingoGetStatsDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientToGCBingoGetStatsDataResponse.ProtoReflect.Descriptor instead.
func (*CMsgClientToGCBingoGetStatsDataResponse) Descriptor() ([]byte, []int) {
	return file_dota_gcmessages_client_bingo_proto_rawDescGZIP(), []int{7}
}

func (x *CMsgClientToGCBingoGetStatsDataResponse) GetResponse() CMsgClientToGCBingoGetStatsDataResponse_EResponse {
	if x != nil && x.Response != nil {
		return *x.Response
	}
	return Default_CMsgClientToGCBingoGetStatsDataResponse_Response
}

func (x *CMsgClientToGCBingoGetStatsDataResponse) GetStatsData() *CMsgBingoStatsData {
	if x != nil {
		return x.StatsData
	}
	return nil
}

type CMsgGCToClientBingoUserDataUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeagueId      *uint32                `protobuf:"varint,1,opt,name=league_id,json=leagueId" json:"league_id,omitempty"`
	LeaguePhase   *uint32                `protobuf:"varint,2,opt,name=league_phase,json=leaguePhase" json:"league_phase,omitempty"`
	UserData      *CMsgBingoUserData     `protobuf:"bytes,3,opt,name=user_data,json=userData" json:"user_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgGCToClientBingoUserDataUpdated) Reset() {
	*x = CMsgGCToClientBingoUserDataUpdated{}
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgGCToClientBingoUserDataUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgGCToClientBingoUserDataUpdated) ProtoMessage() {}

func (x *CMsgGCToClientBingoUserDataUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgGCToClientBingoUserDataUpdated.ProtoReflect.Descriptor instead.
func (*CMsgGCToClientBingoUserDataUpdated) Descriptor() ([]byte, []int) {
	return file_dota_gcmessages_client_bingo_proto_rawDescGZIP(), []int{8}
}

func (x *CMsgGCToClientBingoUserDataUpdated) GetLeagueId() uint32 {
	if x != nil && x.LeagueId != nil {
		return *x.LeagueId
	}
	return 0
}

func (x *CMsgGCToClientBingoUserDataUpdated) GetLeaguePhase() uint32 {
	if x != nil && x.LeaguePhase != nil {
		return *x.LeaguePhase
	}
	return 0
}

func (x *CMsgGCToClientBingoUserDataUpdated) GetUserData() *CMsgBingoUserData {
	if x != nil {
		return x.UserData
	}
	return nil
}

type CMsgClientToGCBingoClaimRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeagueId      *uint32                `protobuf:"varint,1,opt,name=league_id,json=leagueId" json:"league_id,omitempty"`
	LeaguePhase   *uint32                `protobuf:"varint,2,opt,name=league_phase,json=leaguePhase" json:"league_phase,omitempty"`
	RowIndex      *uint32                `protobuf:"varint,3,opt,name=row_index,json=rowIndex" json:"row_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientToGCBingoClaimRow) Reset() {
	*x = CMsgClientToGCBingoClaimRow{}
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientToGCBingoClaimRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientToGCBingoClaimRow) ProtoMessage() {}

func (x *CMsgClientToGCBingoClaimRow) ProtoReflect() protoreflect.Message {
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientToGCBingoClaimRow.ProtoReflect.Descriptor instead.
func (*CMsgClientToGCBingoClaimRow) Descriptor() ([]byte, []int) {
	return file_dota_gcmessages_client_bingo_proto_rawDescGZIP(), []int{9}
}

func (x *CMsgClientToGCBingoClaimRow) GetLeagueId() uint32 {
	if x != nil && x.LeagueId != nil {
		return *x.LeagueId
	}
	return 0
}

func (x *CMsgClientToGCBingoClaimRow) GetLeaguePhase() uint32 {
	if x != nil && x.LeaguePhase != nil {
		return *x.LeaguePhase
	}
	return 0
}

func (x *CMsgClientToGCBingoClaimRow) GetRowIndex() uint32 {
	if x != nil && x.RowIndex != nil {
		return *x.RowIndex
	}
	return 0
}

type CMsgClientToGCBingoClaimRowResponse struct {
	state         protoimpl.MessageState                         `protogen:"open.v1"`
	Response      *CMsgClientToGCBingoClaimRowResponse_EResponse `protobuf:"varint,1,opt,name=response,enum=protocol.CMsgClientToGCBingoClaimRowResponse_EResponse,def=0" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CMsgClientToGCBingoClaimRowResponse fields.
const (
	Default_CMsgClientToGCBingoClaimRowResponse_Response = CMsgClientToGCBingoClaimRowResponse_k_eInternalError
)

func (x *CMsgClientToGCBingoClaimRowResponse) Reset() {
	*x = CMsgClientToGCBingoClaimRowResponse{}
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientToGCBingoClaimRowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientToGCBingoClaimRowResponse) ProtoMessage() {}

func (x *CMsgClientToGCBingoClaimRowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientToGCBingoClaimRowResponse.ProtoReflect.Descriptor instead.
func (*CMsgClientToGCBingoClaimRowResponse) Descriptor() ([]byte, []int) {
	return file_dota_gcmessages_client_bingo_proto_rawDescGZIP(), []int{10}
}

func (x *CMsgClientToGCBingoClaimRowResponse) GetResponse() CMsgClientToGCBingoClaimRowResponse_EResponse {
	if x != nil && x.Response != nil {
		return *x.Response
	}
	return Default_CMsgClientToGCBingoClaimRowResponse_Response
}

type CMsgClientToGCBingoDevRerollCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeagueId      *uint32                `protobuf:"varint,1,opt,name=league_id,json=leagueId" json:"league_id,omitempty"`
	LeaguePhase   *uint32                `protobuf:"varint,2,opt,name=league_phase,json=leaguePhase" json:"league_phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CMsgClientToGCBingoDevRerollCard) Reset() {
	*x = CMsgClientToGCBingoDevRerollCard{}
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientToGCBingoDevRerollCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientToGCBingoDevRerollCard) ProtoMessage() {}

func (x *CMsgClientToGCBingoDevRerollCard) ProtoReflect() protoreflect.Message {
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientToGCBingoDevRerollCard.ProtoReflect.Descriptor instead.
func (*CMsgClientToGCBingoDevRerollCard) Descriptor() ([]byte, []int) {
	return file_dota_gcmessages_client_bingo_proto_rawDescGZIP(), []int{11}
}

func (x *CMsgClientToGCBingoDevRerollCard) GetLeagueId() uint32 {
	if x != nil && x.LeagueId != nil {
		return *x.LeagueId
	}
	return 0
}

func (x *CMsgClientToGCBingoDevRerollCard) GetLeaguePhase() uint32 {
	if x != nil && x.LeaguePhase != nil {
		return *x.LeaguePhase
	}
	return 0
}

type CMsgClientToGCBingoDevRerollCardResponse struct {
	state         protoimpl.MessageState                              `protogen:"open.v1"`
	Response      *CMsgClientToGCBingoDevRerollCardResponse_EResponse `protobuf:"varint,1,opt,name=response,enum=protocol.CMsgClientToGCBingoDevRerollCardResponse_EResponse,def=0" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for CMsgClientToGCBingoDevRerollCardResponse fields.
const (
	Default_CMsgClientToGCBingoDevRerollCardResponse_Response = CMsgClientToGCBingoDevRerollCardResponse_k_eInternalError
)

func (x *CMsgClientToGCBingoDevRerollCardResponse) Reset() {
	*x = CMsgClientToGCBingoDevRerollCardResponse{}
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CMsgClientToGCBingoDevRerollCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMsgClientToGCBingoDevRerollCardResponse) ProtoMessage() {}

func (x *CMsgClientToGCBingoDevRerollCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dota_gcmessages_client_bingo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMsgClientToGCBingoDevRerollCardResponse.ProtoReflect.Descriptor instead.
func (*CMsgClientToGCBingoDevRerollCardResponse) Descriptor() ([]byte, []int) {
	return file_dota_gcmessages_client_bingo_proto_rawDescGZIP(), []int{12}
}

func (x *CMsgClientToGCBingoDevRerollCardResponse) GetResponse() CMsgClientToGCBingoDevRerollCardResponse_EResponse {
	if x != nil && x.Response != nil {
		return *x.Response
	}
	return Default_CMsgClientToGCBingoDevRerollCardResponse_Response
}

var File_dota_gcmessages_client_bingo_proto protoreflect.FileDescriptor

const file_dota_gcmessages_client_bingo_proto_rawDesc = "" +
	"\n" +
	"\"dota_gcmessages_client_bingo.proto\x12\bprotocol\x1a\x13steammessages.proto\x1a\x17dota_shared_enums.proto\x1a\x1cdota_gcmessages_common.proto\x1a\x1cdota_gcmessages_webapi.proto\x1a\x16gcsdk_gcmessages.proto\x1a\x15base_gcmessages.proto\x1a\x15econ_gcmessages.proto\x1a\x1cdota_gcmessages_client.proto\x1a\x15valveextensions.proto\"Q\n" +
	"\x0fCMsgBingoSquare\x12\x17\n" +
	"\astat_id\x18\x01 \x01(\rR\x06statId\x12%\n" +
	"\x0estat_threshold\x18\x02 \x01(\x05R\rstatThreshold\"H\n" +
	"\x11CMsgBingoUserData\x123\n" +
	"\asquares\x18\x01 \x03(\v2\x19.protocol.CMsgBingoSquareR\asquares\"`\n" +
	"\x1eCMsgClientToGCBingoGetUserData\x12\x1b\n" +
	"\tleague_id\x18\x01 \x01(\rR\bleagueId\x12!\n" +
	"\fleague_phase\x18\x02 \x01(\rR\vleaguePhase\"\xb0\x02\n" +
	"&CMsgClientToGCBingoGetUserDataResponse\x12h\n" +
	"\bresponse\x18\x01 \x01(\x0e2:.protocol.CMsgClientToGCBingoGetUserDataResponse.EResponse:\x10k_eInternalErrorR\bresponse\x128\n" +
	"\tuser_data\x18\x02 \x01(\v2\x1b.protocol.CMsgBingoUserDataR\buserData\"b\n" +
	"\tEResponse\x12\x14\n" +
	"\x10k_eInternalError\x10\x00\x12\x0e\n" +
	"\n" +
	"k_eSuccess\x10\x01\x12\x0e\n" +
	"\n" +
	"k_eTooBusy\x10\x02\x12\x0f\n" +
	"\vk_eDisabled\x10\x03\x12\x0e\n" +
	"\n" +
	"k_eTimeout\x10\x04\"U\n" +
	"\x1bCMsgBingoIndividualStatData\x12\x17\n" +
	"\astat_id\x18\x01 \x01(\rR\x06statId\x12\x1d\n" +
	"\n" +
	"stat_value\x18\x02 \x01(\x05R\tstatValue\"Z\n" +
	"\x12CMsgBingoStatsData\x12D\n" +
	"\n" +
	"stats_data\x18\x01 \x03(\v2%.protocol.CMsgBingoIndividualStatDataR\tstatsData\"a\n" +
	"\x1fCMsgClientToGCBingoGetStatsData\x12\x1b\n" +
	"\tleague_id\x18\x01 \x01(\rR\bleagueId\x12!\n" +
	"\fleague_phase\x18\x02 \x01(\rR\vleaguePhase\"\xb5\x02\n" +
	"'CMsgClientToGCBingoGetStatsDataResponse\x12i\n" +
	"\bresponse\x18\x01 \x01(\x0e2;.protocol.CMsgClientToGCBingoGetStatsDataResponse.EResponse:\x10k_eInternalErrorR\bresponse\x12;\n" +
	"\n" +
	"stats_data\x18\x02 \x01(\v2\x1c.protocol.CMsgBingoStatsDataR\tstatsData\"b\n" +
	"\tEResponse\x12\x14\n" +
	"\x10k_eInternalError\x10\x00\x12\x0e\n" +
	"\n" +
	"k_eSuccess\x10\x01\x12\x0e\n" +
	"\n" +
	"k_eTooBusy\x10\x02\x12\x0f\n" +
	"\vk_eDisabled\x10\x03\x12\x0e\n" +
	"\n" +
	"k_eTimeout\x10\x04\"\x9e\x01\n" +
	"\"CMsgGCToClientBingoUserDataUpdated\x12\x1b\n" +
	"\tleague_id\x18\x01 \x01(\rR\bleagueId\x12!\n" +
	"\fleague_phase\x18\x02 \x01(\rR\vleaguePhase\x128\n" +
	"\tuser_data\x18\x03 \x01(\v2\x1b.protocol.CMsgBingoUserDataR\buserData\"z\n" +
	"\x1bCMsgClientToGCBingoClaimRow\x12\x1b\n" +
	"\tleague_id\x18\x01 \x01(\rR\bleagueId\x12!\n" +
	"\fleague_phase\x18\x02 \x01(\rR\vleaguePhase\x12\x1b\n" +
	"\trow_index\x18\x03 \x01(\rR\browIndex\"\x98\x02\n" +
	"#CMsgClientToGCBingoClaimRowResponse\x12e\n" +
	"\bresponse\x18\x01 \x01(\x0e27.protocol.CMsgClientToGCBingoClaimRowResponse.EResponse:\x10k_eInternalErrorR\bresponse\"\x89\x01\n" +
	"\tEResponse\x12\x14\n" +
	"\x10k_eInternalError\x10\x00\x12\x0e\n" +
	"\n" +
	"k_eSuccess\x10\x01\x12\x0e\n" +
	"\n" +
	"k_eTooBusy\x10\x02\x12\x0f\n" +
	"\vk_eDisabled\x10\x03\x12\x0e\n" +
	"\n" +
	"k_eTimeout\x10\x04\x12\x11\n" +
	"\rk_eInvalidRow\x10\x05\x12\x12\n" +
	"\x0ek_eExpiredCard\x10\x06\"b\n" +
	" CMsgClientToGCBingoDevRerollCard\x12\x1b\n" +
	"\tleague_id\x18\x01 \x01(\rR\bleagueId\x12!\n" +
	"\fleague_phase\x18\x02 \x01(\rR\vleaguePhase\"\xa2\x02\n" +
	"(CMsgClientToGCBingoDevRerollCardResponse\x12j\n" +
	"\bresponse\x18\x01 \x01(\x0e2<.protocol.CMsgClientToGCBingoDevRerollCardResponse.EResponse:\x10k_eInternalErrorR\bresponse\"\x89\x01\n" +
	"\tEResponse\x12\x14\n" +
	"\x10k_eInternalError\x10\x00\x12\x0e\n" +
	"\n" +
	"k_eSuccess\x10\x01\x12\x0e\n" +
	"\n" +
	"k_eTooBusy\x10\x02\x12\x0f\n" +
	"\vk_eDisabled\x10\x03\x12\x0e\n" +
	"\n" +
	"k_eTimeout\x10\x04\x12\x12\n" +
	"\x0ek_eExpiredCard\x10\x06\x12\x11\n" +
	"\rk_eNotAllowed\x10\aB\rZ\v./;protocol"

var (
	file_dota_gcmessages_client_bingo_proto_rawDescOnce sync.Once
	file_dota_gcmessages_client_bingo_proto_rawDescData []byte
)

func file_dota_gcmessages_client_bingo_proto_rawDescGZIP() []byte {
	file_dota_gcmessages_client_bingo_proto_rawDescOnce.Do(func() {
		file_dota_gcmessages_client_bingo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dota_gcmessages_client_bingo_proto_rawDesc), len(file_dota_gcmessages_client_bingo_proto_rawDesc)))
	})
	return file_dota_gcmessages_client_bingo_proto_rawDescData
}

var file_dota_gcmessages_client_bingo_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_dota_gcmessages_client_bingo_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_dota_gcmessages_client_bingo_proto_goTypes = []any{
	(CMsgClientToGCBingoGetUserDataResponse_EResponse)(0),   // 0: protocol.CMsgClientToGCBingoGetUserDataResponse.EResponse
	(CMsgClientToGCBingoGetStatsDataResponse_EResponse)(0),  // 1: protocol.CMsgClientToGCBingoGetStatsDataResponse.EResponse
	(CMsgClientToGCBingoClaimRowResponse_EResponse)(0),      // 2: protocol.CMsgClientToGCBingoClaimRowResponse.EResponse
	(CMsgClientToGCBingoDevRerollCardResponse_EResponse)(0), // 3: protocol.CMsgClientToGCBingoDevRerollCardResponse.EResponse
	(*CMsgBingoSquare)(nil),                                 // 4: protocol.CMsgBingoSquare
	(*CMsgBingoUserData)(nil),                               // 5: protocol.CMsgBingoUserData
	(*CMsgClientToGCBingoGetUserData)(nil),                  // 6: protocol.CMsgClientToGCBingoGetUserData
	(*CMsgClientToGCBingoGetUserDataResponse)(nil),          // 7: protocol.CMsgClientToGCBingoGetUserDataResponse
	(*CMsgBingoIndividualStatData)(nil),                     // 8: protocol.CMsgBingoIndividualStatData
	(*CMsgBingoStatsData)(nil),                              // 9: protocol.CMsgBingoStatsData
	(*CMsgClientToGCBingoGetStatsData)(nil),                 // 10: protocol.CMsgClientToGCBingoGetStatsData
	(*CMsgClientToGCBingoGetStatsDataResponse)(nil),         // 11: protocol.CMsgClientToGCBingoGetStatsDataResponse
	(*CMsgGCToClientBingoUserDataUpdated)(nil),              // 12: protocol.CMsgGCToClientBingoUserDataUpdated
	(*CMsgClientToGCBingoClaimRow)(nil),                     // 13: protocol.CMsgClientToGCBingoClaimRow
	(*CMsgClientToGCBingoClaimRowResponse)(nil),             // 14: protocol.CMsgClientToGCBingoClaimRowResponse
	(*CMsgClientToGCBingoDevRerollCard)(nil),                // 15: protocol.CMsgClientToGCBingoDevRerollCard
	(*CMsgClientToGCBingoDevRerollCardResponse)(nil),        // 16: protocol.CMsgClientToGCBingoDevRerollCardResponse
}
var file_dota_gcmessages_client_bingo_proto_depIdxs = []int32{
	4, // 0: protocol.CMsgBingoUserData.squares:type_name -> protocol.CMsgBingoSquare
	0, // 1: protocol.CMsgClientToGCBingoGetUserDataResponse.response:type_name -> protocol.CMsgClientToGCBingoGetUserDataResponse.EResponse
	5, // 2: protocol.CMsgClientToGCBingoGetUserDataResponse.user_data:type_name -> protocol.CMsgBingoUserData
	8, // 3: protocol.CMsgBingoStatsData.stats_data:type_name -> protocol.CMsgBingoIndividualStatData
	1, // 4: protocol.CMsgClientToGCBingoGetStatsDataResponse.response:type_name -> protocol.CMsgClientToGCBingoGetStatsDataResponse.EResponse
	9, // 5: protocol.CMsgClientToGCBingoGetStatsDataResponse.stats_data:type_name -> protocol.CMsgBingoStatsData
	5, // 6: protocol.CMsgGCToClientBingoUserDataUpdated.user_data:type_name -> protocol.CMsgBingoUserData
	2, // 7: protocol.CMsgClientToGCBingoClaimRowResponse.response:type_name -> protocol.CMsgClientToGCBingoClaimRowResponse.EResponse
	3, // 8: protocol.CMsgClientToGCBingoDevRerollCardResponse.response:type_name -> protocol.CMsgClientToGCBingoDevRerollCardResponse.EResponse
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_dota_gcmessages_client_bingo_proto_init() }
func file_dota_gcmessages_client_bingo_proto_init() {
	if File_dota_gcmessages_client_bingo_proto != nil {
		return
	}
	file_steammessages_proto_init()
	file_dota_shared_enums_proto_init()
	file_dota_gcmessages_common_proto_init()
	file_dota_gcmessages_webapi_proto_init()
	file_gcsdk_gcmessages_proto_init()
	file_base_gcmessages_proto_init()
	file_econ_gcmessages_proto_init()
	file_dota_gcmessages_client_proto_init()
	file_valveextensions_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dota_gcmessages_client_bingo_proto_rawDesc), len(file_dota_gcmessages_client_bingo_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dota_gcmessages_client_bingo_proto_goTypes,
		DependencyIndexes: file_dota_gcmessages_client_bingo_proto_depIdxs,
		EnumInfos:         file_dota_gcmessages_client_bingo_proto_enumTypes,
		MessageInfos:      file_dota_gcmessages_client_bingo_proto_msgTypes,
	}.Build()
	File_dota_gcmessages_client_bingo_proto = out.File
	file_dota_gcmessages_client_bingo_proto_goTypes = nil
	file_dota_gcmessages_client_bingo_proto_depIdxs = nil
}
