// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: valveextensions.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_valveextensions_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         61000,
		Name:          "protocol.valve_map_field",
		Tag:           "varint,61000,opt,name=valve_map_field,def=0",
		Filename:      "valveextensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         61001,
		Name:          "protocol.valve_map_key",
		Tag:           "varint,61001,opt,name=valve_map_key,def=0",
		Filename:      "valveextensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         61002,
		Name:          "protocol.diff_encode_field",
		Tag:           "varint,61002,opt,name=diff_encode_field,def=0",
		Filename:      "valveextensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         61003,
		Name:          "protocol.delta_ignore",
		Tag:           "varint,61003,opt,name=delta_ignore,def=0",
		Filename:      "valveextensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         61004,
		Name:          "protocol.steamml_max_entries",
		Tag:           "varint,61004,opt,name=steamml_max_entries,def=0",
		Filename:      "valveextensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         61005,
		Name:          "protocol.steamml_is_timestamp",
		Tag:           "varint,61005,opt,name=steamml_is_timestamp,def=0",
		Filename:      "valveextensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         61006,
		Name:          "protocol.steamlearn_count",
		Tag:           "varint,61006,opt,name=steamlearn_count,def=0",
		Filename:      "valveextensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         1000,
		Name:          "protocol.schema_friendly_name",
		Tag:           "bytes,1000,opt,name=schema_friendly_name",
		Filename:      "valveextensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         1001,
		Name:          "protocol.schema_description",
		Tag:           "bytes,1001,opt,name=schema_description",
		Filename:      "valveextensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1002,
		Name:          "protocol.schema_suppress_enumerator",
		Tag:           "varint,1002,opt,name=schema_suppress_enumerator",
		Filename:      "valveextensions.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool valve_map_field = 61000;
	E_ValveMapField = &file_valveextensions_proto_extTypes[0]
	// optional bool valve_map_key = 61001;
	E_ValveMapKey = &file_valveextensions_proto_extTypes[1]
	// optional int32 diff_encode_field = 61002;
	E_DiffEncodeField = &file_valveextensions_proto_extTypes[2]
	// optional bool delta_ignore = 61003;
	E_DeltaIgnore = &file_valveextensions_proto_extTypes[3]
	// optional uint32 steamml_max_entries = 61004;
	E_SteammlMaxEntries = &file_valveextensions_proto_extTypes[4]
	// optional bool steamml_is_timestamp = 61005;
	E_SteammlIsTimestamp = &file_valveextensions_proto_extTypes[5]
	// optional uint32 steamlearn_count = 61006;
	E_SteamlearnCount = &file_valveextensions_proto_extTypes[6]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional string schema_friendly_name = 1000;
	E_SchemaFriendlyName = &file_valveextensions_proto_extTypes[7]
	// optional string schema_description = 1001;
	E_SchemaDescription = &file_valveextensions_proto_extTypes[8]
	// optional bool schema_suppress_enumerator = 1002;
	E_SchemaSuppressEnumerator = &file_valveextensions_proto_extTypes[9]
)

var File_valveextensions_proto protoreflect.FileDescriptor

const file_valveextensions_proto_rawDesc = "" +
	"\n" +
	"\x15valveextensions.proto\x12\bprotocol\x1a google/protobuf/descriptor.proto:N\n" +
	"\x0fvalve_map_field\x12\x1d.google.protobuf.FieldOptions\x18\xc8\xdc\x03 \x01(\b:\x05falseR\rvalveMapField:J\n" +
	"\rvalve_map_key\x12\x1d.google.protobuf.FieldOptions\x18\xc9\xdc\x03 \x01(\b:\x05falseR\vvalveMapKey:N\n" +
	"\x11diff_encode_field\x12\x1d.google.protobuf.FieldOptions\x18\xca\xdc\x03 \x01(\x05:\x010R\x0fdiffEncodeField:I\n" +
	"\fdelta_ignore\x12\x1d.google.protobuf.FieldOptions\x18\xcb\xdc\x03 \x01(\b:\x05falseR\vdeltaIgnore:R\n" +
	"\x13steamml_max_entries\x12\x1d.google.protobuf.FieldOptions\x18\xcc\xdc\x03 \x01(\r:\x010R\x11steammlMaxEntries:X\n" +
	"\x14steamml_is_timestamp\x12\x1d.google.protobuf.FieldOptions\x18\xcd\xdc\x03 \x01(\b:\x05falseR\x12steammlIsTimestamp:M\n" +
	"\x10steamlearn_count\x12\x1d.google.protobuf.FieldOptions\x18\xce\xdc\x03 \x01(\r:\x010R\x0fsteamlearnCount:T\n" +
	"\x14schema_friendly_name\x12!.google.protobuf.EnumValueOptions\x18\xe8\a \x01(\tR\x12schemaFriendlyName:Q\n" +
	"\x12schema_description\x12!.google.protobuf.EnumValueOptions\x18\xe9\a \x01(\tR\x11schemaDescription:`\n" +
	"\x1aschema_suppress_enumerator\x12!.google.protobuf.EnumValueOptions\x18\xea\a \x01(\bR\x18schemaSuppressEnumeratorB\rZ\v./;protocol"

var file_valveextensions_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil),     // 0: google.protobuf.FieldOptions
	(*descriptorpb.EnumValueOptions)(nil), // 1: google.protobuf.EnumValueOptions
}
var file_valveextensions_proto_depIdxs = []int32{
	0,  // 0: protocol.valve_map_field:extendee -> google.protobuf.FieldOptions
	0,  // 1: protocol.valve_map_key:extendee -> google.protobuf.FieldOptions
	0,  // 2: protocol.diff_encode_field:extendee -> google.protobuf.FieldOptions
	0,  // 3: protocol.delta_ignore:extendee -> google.protobuf.FieldOptions
	0,  // 4: protocol.steamml_max_entries:extendee -> google.protobuf.FieldOptions
	0,  // 5: protocol.steamml_is_timestamp:extendee -> google.protobuf.FieldOptions
	0,  // 6: protocol.steamlearn_count:extendee -> google.protobuf.FieldOptions
	1,  // 7: protocol.schema_friendly_name:extendee -> google.protobuf.EnumValueOptions
	1,  // 8: protocol.schema_description:extendee -> google.protobuf.EnumValueOptions
	1,  // 9: protocol.schema_suppress_enumerator:extendee -> google.protobuf.EnumValueOptions
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	0,  // [0:10] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_valveextensions_proto_init() }
func file_valveextensions_proto_init() {
	if File_valveextensions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_valveextensions_proto_rawDesc), len(file_valveextensions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 10,
			NumServices:   0,
		},
		GoTypes:           file_valveextensions_proto_goTypes,
		DependencyIndexes: file_valveextensions_proto_depIdxs,
		ExtensionInfos:    file_valveextensions_proto_extTypes,
	}.Build()
	File_valveextensions_proto = out.File
	file_valveextensions_proto_goTypes = nil
	file_valveextensions_proto_depIdxs = nil
}
