// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: valve_extensions.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_valve_extensions_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "protocol.boxed_type",
		Tag:           "bytes,50001,opt,name=boxed_type",
		Filename:      "valve_extensions.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50002,
		Name:          "protocol.additional_includes",
		Tag:           "bytes,50002,opt,name=additional_includes",
		Filename:      "valve_extensions.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string boxed_type = 50001;
	E_BoxedType = &file_valve_extensions_proto_extTypes[0]
)

// Extension fields to descriptorpb.FileOptions.
var (
	// optional string additional_includes = 50002;
	E_AdditionalIncludes = &file_valve_extensions_proto_extTypes[1]
)

var File_valve_extensions_proto protoreflect.FileDescriptor

const file_valve_extensions_proto_rawDesc = "" +
	"\n" +
	"\x16valve_extensions.proto\x12\bprotocol\x1a google/protobuf/descriptor.proto:>\n" +
	"\n" +
	"boxed_type\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\tR\tboxedType:O\n" +
	"\x13additional_includes\x12\x1c.google.protobuf.FileOptions\x18҆\x03 \x01(\tR\x12additionalIncludesB\rZ\v./;protocol"

var file_valve_extensions_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
	(*descriptorpb.FileOptions)(nil),  // 1: google.protobuf.FileOptions
}
var file_valve_extensions_proto_depIdxs = []int32{
	0, // 0: protocol.boxed_type:extendee -> google.protobuf.FieldOptions
	1, // 1: protocol.additional_includes:extendee -> google.protobuf.FileOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_valve_extensions_proto_init() }
func file_valve_extensions_proto_init() {
	if File_valve_extensions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_valve_extensions_proto_rawDesc), len(file_valve_extensions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_valve_extensions_proto_goTypes,
		DependencyIndexes: file_valve_extensions_proto_depIdxs,
		ExtensionInfos:    file_valve_extensions_proto_extTypes,
	}.Build()
	File_valve_extensions_proto = out.File
	file_valve_extensions_proto_goTypes = nil
	file_valve_extensions_proto_depIdxs = nil
}
